### ISSUE TITLE
Source of 2.6 version?

### ISSUE THREAD

**Issue by nickd4** [zvezdochiot/bas#1]
Hi, may I ask where the version 2.6 version in tag `2.6` came from? As the author's website only seems to contain `bas-2.5.tar.gz` which I thought was the latest until now. Or are you the author?

Thanks!

**Comment by zvezdochiot** [comment]
Hi @nickd4 

I made some changes. It was impossible to leave the previous version.

PS: See link in https://github.com/zvezdochiot/bas/releases/tag/2.6

**Comment by nickd4** [comment]
Thankyou, that clears things up. By the way, it seems like the fossies version is downloaded from this one: http://www.moria.de/~michael/bas/bas-2.6.tar.gz and that link works even though the text at http://www.moria.de/~michael/bas only contains the link to 2.5 version!
